import { useState, useEffect, useCallback, useRef } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../../api'
import { useLanguage } from '../../i18n'

// ── Task type metadata ────────────────────────────────────────────────────────
const TASK_TYPES = [
  { value: 'EMPAQUE',             label: 'Empaque',              bg: '#dbeafe', color: '#1d4ed8' },
  { value: 'MUDANZA',             label: 'Mudanza',              bg: '#e0e7ff', color: '#4338ca' },
  { value: 'DESEMPAQUE',          label: 'Desempaque',           bg: '#ccfbf1', color: '#0f766e' },
  { value: 'CARGA_CONTENEDOR',    label: 'Carga Contenedor',     bg: '#ffedd5', color: '#c2410c' },
  { value: 'TRABAJO_INDUSTRIAL',  label: 'Trabajo Industrial',   bg: '#fef9c3', color: '#a16207' },
  { value: 'ENTREGA',             label: 'Entrega',              bg: '#dcfce7', color: '#15803d' },
  { value: 'TRASLADO_BODEGA',     label: 'Traslado Bodega',      bg: '#fef3c7', color: '#b45309' },
  { value: 'VISITA',              label: 'Visita',               bg: '#f3e8ff', color: '#7e22ce' },
  { value: 'OTRO',                label: 'Otro',                 bg: '#f1f5f9', color: '#475569' },
]
const taskMeta = (type) => TASK_TYPES.find(t => t.value === type) || TASK_TYPES[TASK_TYPES.length - 1]

const MONTH_NAMES_ES = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']

function pad2(n) { return String(n).padStart(2, '0') }
function toDateStr(d) { return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}` }
function fromDateStr(str) { return new Date(`${str}T12:00:00`) }
function expandDateRange(startStr, endStr) {
  const days = []
  const cursor = fromDateStr(startStr)
  const end = fromDateStr(endStr)
  while (cursor <= end) {
    days.push(toDateStr(cursor))
    cursor.setDate(cursor.getDate() + 1)
  }
  return days
}
function formatRangeLabel(startStr, endStr) {
  if (!startStr || !endStr || startStr === endStr) return null
  return `${startStr} → ${endStr}`
}
function entryStartStr(entry) { return (entry.startDate || entry.date).slice(0, 10) }
function entryEndStr(entry) { return (entry.endDate || entry.startDate || entry.date).slice(0, 10) }

// ── Empty form ────────────────────────────────────────────────────────────────
const EMPTY_FORM = {
  startDate: '', endDate: '', time: '', taskType: 'EMPAQUE', description: '', notes: '',
  jobId: '', assignedToId: '',
}

// ── Linked record chip ────────────────────────────────────────────────────────
function LinkedChip({ entry }) {
  if (entry.job) {
    return (
      <Link
        to={`/jobs/${entry.job.id}`}
        className="badge"
        onClick={e => e.stopPropagation()}
        onMouseDown={e => e.stopPropagation()}
        style={{ background:'#e0f2fe', color:'#0369a1', textDecoration:'none', fontSize:11 }}
      >
        #{entry.job.jobNumber}
      </Link>
    )
  }
  return null
}

// ── Create/Edit Modal ─────────────────────────────────────────────────────────
function EntryModal({ entry, defaultDate, onClose, onSaved }) {
  const { t } = useLanguage()
  const isEdit = Boolean(entry?.id)
  const isSystem = isEdit && Boolean(entry.isAutoGenerated)
  const [form, setForm] = useState(EMPTY_FORM)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState(null)
  const [staffList, setStaffList] = useState([])
  const [jobSearch, setJobSearch] = useState('')
  const [jobResults, setJobResults] = useState([])
  const [jobSearching, setJobSearching] = useState(false)
  const [selectedJob, setSelectedJob] = useState(null)

  useEffect(() => {
    api.get('/staff').then(setStaffList).catch(() => {})
  }, [])

  useEffect(() => {
    if (entry) {
      setForm({
        startDate:    entryStartStr(entry),
        endDate:      entryEndStr(entry),
        time:         entry.time         || '',
        taskType:     entry.taskType,
        description:  entry.description,
        notes:        entry.notes        || '',
        jobId:        entry.jobId        || '',
        assignedToId: entry.assignedToId || '',
      })
      setSelectedJob(entry.job || null)
    } else {
      setForm({ ...EMPTY_FORM, startDate: defaultDate || '', endDate: defaultDate || '' })
      setSelectedJob(null)
    }
  }, [entry, defaultDate])

  // Debounced job search
  useEffect(() => {
    if (!jobSearch.trim() || form.jobId) { setJobResults([]); return }
    const t = setTimeout(() => {
      setJobSearching(true)
      api.get(`/jobs?search=${encodeURIComponent(jobSearch.trim())}`)
        .then(data => setJobResults((data || []).slice(0, 8)))
        .catch(() => setJobResults([]))
        .finally(() => setJobSearching(false))
    }, 300)
    return () => clearTimeout(t)
  }, [jobSearch, form.jobId])

  const set = (f, v) => setForm(p => ({ ...p, [f]: v }))

  const handleSubmit = async (e) => {
    e.preventDefault()
    setSaving(true)
    setError(null)
    try {
      if (form.startDate && form.endDate && form.startDate > form.endDate) throw new Error(t('schedule.rangeInvalid'))
      const payload = {
        startDate:    form.startDate,
        endDate:      form.endDate,
        time:         form.time || null,
        taskType:     form.taskType,
        description:  form.description,
        notes:        form.notes        || null,
        jobId:        form.jobId        || null,
        assignedToId: form.assignedToId || null,
      }
      const saved = isEdit
        ? await api.put(`/schedule/${entry.id}`, payload)
        : await api.post('/schedule', payload)
      onSaved(saved, isEdit)
    } catch (err) {
      setError(err.message)
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!window.confirm(t('schedule.deleteEntryConfirm'))) return
    setSaving(true)
    setError(null)
    try {
      await api.delete(`/schedule/${entry.id}`)
      onSaved(null, 'delete', entry.id)
    } catch (err) {
      setError(err.message)
      setSaving(false)
    }
  }

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.45)', zIndex:1000, display:'flex', alignItems:'center', justifyContent:'center', padding:16 }}>
      <div style={{ background:'#fff', borderRadius:12, padding:24, width:'100%', maxWidth:480, maxHeight:'90vh', overflowY:'auto', boxShadow:'0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:20 }}>
          <h3 style={{ margin:0, fontSize:16, fontWeight:700 }}>{isEdit ? t('schedule.editEntry') : t('schedule.newEntry')}</h3>
          <button onClick={onClose} style={{ background:'none', border:'none', fontSize:20, cursor:'pointer', color:'#64748b' }}>✕</button>
        </div>

        <form onSubmit={handleSubmit} style={{ display:'flex', flexDirection:'column', gap:14 }}>

          {/* ── Job link — top of form ── */}
          {(selectedJob || !isSystem) && (
            <div className="form-group">
              <label className="form-label">{isSystem ? t('schedule.linkedJob') : t('schedule.linkJobOptional')}</label>
              {form.jobId && selectedJob ? (
                <div style={{ display:'flex', alignItems:'center', gap:8, padding:'8px 10px', background:'#e0f2fe', borderRadius:6 }}>
                  <Link
                    to={`/jobs/${selectedJob.id}`}
                    onClick={e => e.stopPropagation()}
                    style={{ fontWeight:700, fontSize:13, color:'#0369a1', textDecoration:'none' }}
                  >
                    #{selectedJob.jobNumber}
                  </Link>
                  {selectedJob.type && <span style={{ fontSize:11, fontWeight:600, background:'#bfdbfe', color:'#1d4ed8', borderRadius:4, padding:'1px 6px' }}>{selectedJob.type}</span>}
                  <span style={{ flex:1, fontSize:13, color:'#0369a1' }}>{selectedJob.quoteTo || selectedJob.client?.name || selectedJob.companyName || '—'}</span>
                  {!isSystem && <button type="button"
                    onClick={() => { set('jobId', ''); setSelectedJob(null); setJobSearch('') }}
                    style={{ background:'none', border:'none', color:'#64748b', cursor:'pointer', fontSize:16, lineHeight:1 }}>✕</button>}
                </div>
              ) : (
                !isSystem && <div style={{ position:'relative' }}>
                  <input className="form-control" placeholder={t('schedule.searchJobsPlaceholder')}
                    value={jobSearch} onChange={e => setJobSearch(e.target.value)} />
                  {jobSearching && <div style={{ fontSize:12, color:'#64748b', marginTop:4 }}>{t('schedule.searching')}</div>}
                  {jobResults.length > 0 && (
                    <div style={{ position:'absolute', top:'100%', left:0, right:0, background:'#fff', border:'1px solid #e2e8f0', borderRadius:8, boxShadow:'0 4px 16px rgba(0,0,0,0.12)', zIndex:20, maxHeight:200, overflowY:'auto', marginTop:2 }}>
                      {jobResults.map(j => {
                          const typeColors = { EXPORT:'#dbeafe|#1d4ed8', IMPORT:'#dcfce7|#15803d', INTERNATIONAL:'#f3e8ff|#7e22ce', DOMESTIC:'#fef9c3|#a16207' }
                          const [tbg, tcol] = (typeColors[j.type] || '#f1f5f9|#475569').split('|')
                          return (
                            <div key={j.id}
                              onMouseDown={e => e.preventDefault()}
                              onClick={() => {
                                const taskType = { EXPORT: 'EMPAQUE', IMPORT: 'DESEMPAQUE' }[j.type] || 'MUDANZA'
                                const description = j.quoteTo || j.client?.name || j.companyName || ''
                                const noteParts = []
                                if (j.shipmentMode) noteParts.push(j.shipmentMode)
                                const origin = [j.originCity, j.originCountry].filter(Boolean).join(', ')
                                const dest   = [j.destCity,   j.destCountry  ].filter(Boolean).join(', ')
                                if (origin || dest) noteParts.push([origin && `Origen: ${origin}`, dest && `Destino: ${dest}`].filter(Boolean).join(' \u2192 '))
                                const measures = []
                                if (j.volumeCbm != null) measures.push(`${j.volumeCbm} m\u00b3`)
                                if (j.weightKg  != null) measures.push(`${j.weightKg} kg`)
                                if (j.bultos    != null) measures.push(`${j.bultos} bultos`)
                                if (measures.length) noteParts.push(measures.join(' \u00b7 '))
                                if (j.serviceDetails) noteParts.push(j.serviceDetails)
                                setForm(p => ({
                                  ...p,
                                  jobId:       j.id,
                                  taskType,
                                  description,
                                  startDate:   j.serviceDate ? j.serviceDate.slice(0, 10) : p.startDate,
                                  endDate:     j.serviceDate ? j.serviceDate.slice(0, 10) : p.endDate,
                                  time:        j.serviceTime || p.time,
                                  notes:       noteParts.length ? noteParts.join('\n') : p.notes,
                                }))
                                setSelectedJob(j)
                                setJobSearch('')
                                setJobResults([])
                              }}
                              style={{ padding:'8px 12px', cursor:'pointer', borderBottom:'1px solid #f1f5f9', fontSize:13, display:'flex', alignItems:'center', gap:8 }}
                            >
                              <span style={{ fontWeight:700 }}>#{j.jobNumber}</span>
                              {j.type && <span style={{ background:tbg, color:tcol, borderRadius:4, padding:'1px 6px', fontSize:11, fontWeight:600 }}>{j.type}</span>}
                              <span style={{ color:'#64748b' }}>{j.quoteTo || j.client?.name || j.companyName || '—'}</span>
                            </div>
                          )
                        })}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12 }}>
            <div className="form-group">
              <label className="form-label">{t('schedule.startDate')} *</label>
              <input className="form-control" type="date" value={form.startDate} onChange={e => set('startDate', e.target.value)}
                required />
            </div>
            <div className="form-group">
              <label className="form-label">{t('schedule.endDate')} *</label>
              <input className="form-control" type="date" value={form.endDate} onChange={e => set('endDate', e.target.value)} required />
            </div>
          </div>

          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12 }}>
            <div className="form-group">
              <label className="form-label">{t('schedule.time')} *</label>
              <input className="form-control" type="time" value={form.time}
                onChange={e => set('time', e.target.value)} required />
            </div>
            <div />
          </div>

          <div className="form-group">
            <label className="form-label">{t('schedule.taskType')} *</label>
            <select className="form-control" value={form.taskType} onChange={e => set('taskType', e.target.value)} required>
              {TASK_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
            </select>
          </div>

          <div className="form-group">
            <label className="form-label">{t('schedule.clientName')} *</label>
            <input className="form-control" value={form.description} onChange={e => set('description', e.target.value)}
              required placeholder={t('schedule.clientNamePlaceholder')} />
          </div>

          <div className="form-group">
            <label className="form-label">{t('schedule.description')}</label>
            <textarea className="form-control" rows={2} value={form.notes} onChange={e => set('notes', e.target.value)} placeholder={t('schedule.descriptionPlaceholder')} />
          </div>

          <div className="form-group">
            <label className="form-label">{t('schedule.encargado')}</label>
            <select className="form-control" value={form.assignedToId} onChange={e => set('assignedToId', e.target.value)}>
              <option value="">— {t('schedule.unassigned')} —</option>
              {staffList.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>

          {error && <div className="alert alert-error" style={{ fontSize:13 }}>{error}</div>}

          <div style={{ display:'flex', justifyContent:'space-between', marginTop:4 }}>
            {isEdit
              ? <button type="button" onClick={handleDelete} className="btn" style={{ background:'#fee2e2', color:'#b91c1c', border:'none' }} disabled={saving}>Eliminar</button>
              : <span />}
            <div style={{ display:'flex', gap:8 }}>
              <button type="button" className="btn btn-ghost" onClick={onClose} disabled={saving}>{t('common.cancel')}</button>
              <button type="submit" className="btn btn-primary" disabled={saving}>{saving ? t('common.saving') : t('common.save')}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}

// ── Day Panel ─────────────────────────────────────────────────────────────────
function DayPanel({ dateStr, entries, onClose, onAdd, onEdit }) {
  const { t } = useLanguage()
  const dayEntries = [...entries].sort((a, b) => {
    if (!a.time && !b.time) return 0
    if (!a.time) return 1
    if (!b.time) return -1
    return a.time.localeCompare(b.time)
  })
  const d = new Date(dateStr + 'T12:00:00')
  const label = `${d.getDate()} de ${MONTH_NAMES_ES[d.getMonth()]} ${d.getFullYear()}`

  return (
    <div style={{ position:'fixed', inset:0, zIndex:900, display:'flex' }}>
      <div style={{ flex:1 }} onClick={onClose} />
      <div style={{ width: 360, background:'#fff', boxShadow:'-4px 0 24px rgba(0,0,0,0.15)', display:'flex', flexDirection:'column', overflowY:'auto' }}>
        <div style={{ padding:'16px 20px', borderBottom:'1px solid #e2e8f0', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
          <div>
            <div style={{ fontWeight:700, fontSize:15 }}>{label}</div>
            <div style={{ fontSize:12, color:'#64748b' }}>{dayEntries.length} {dayEntries.length === 1 ? t('schedule.entriesCount_one') : t('schedule.entriesCount_other')}</div>
          </div>
          <button onClick={onClose} style={{ background:'none', border:'none', fontSize:20, cursor:'pointer', color:'#64748b' }}>✕</button>
        </div>

        <div style={{ flex:1, padding:'12px 16px', display:'flex', flexDirection:'column', gap:10 }}>
          {dayEntries.length === 0 && <div style={{ color:'#94a3b8', fontSize:13, textAlign:'center', marginTop:16 }}>{t('schedule.noEntriesForDay')}</div>}
          {dayEntries.map(entry => {
            const meta = taskMeta(entry.taskType)
            const rangeLabel = formatRangeLabel(entryStartStr(entry), entryEndStr(entry))
            return (
              <div key={entry.id} onClick={() => onEdit(entry)}
                style={{ border:'1px solid #e2e8f0', borderRadius:8, padding:'10px 12px', cursor:'pointer', background:'#fafafa' }}
              >
                <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:4 }}>
                  <span style={{ background:meta.bg, color:meta.color, borderRadius:4, padding:'2px 7px', fontSize:11, fontWeight:600 }}>{meta.label}</span>
                  {entry.time && <span style={{ fontSize:12, color:'#64748b' }}>{entry.time}</span>}
                  <LinkedChip entry={entry} />
                </div>
                <div style={{ fontSize:14, fontWeight:700, color:'#1e293b' }}>{entry.description}</div>
                {rangeLabel && <div style={{ fontSize:12, color:'#64748b', marginTop:2 }}>🗓 {rangeLabel}</div>}
                {entry.assignedTo && <div style={{ fontSize:12, color:'#0369a1', marginTop:2, fontWeight:600 }}>👤 {entry.assignedTo.name}</div>}
                {entry.notes && <div style={{ fontSize:12, color:'#94a3b8', marginTop:2, fontStyle:'italic' }}>{entry.notes}</div>}
              </div>
            )
          })}
        </div>

        <div style={{ padding:'12px 16px', borderTop:'1px solid #e2e8f0' }}>
          <button className="btn btn-primary" style={{ width:'100%' }} onClick={() => onAdd(dateStr)}>+ {t('schedule.addEntry')}</button>
        </div>
      </div>
    </div>
  )
}

// ── Day Hover Popup ──────────────────────────────────────────────────────────
function DayPopup({ dateStr, entries, rect, onMouseEnter, onMouseLeave }) {
  const { t } = useLanguage()
  if (!entries.length) return null
  const d = new Date(dateStr + 'T12:00:00')
  const label = `${d.getDate()} de ${MONTH_NAMES_ES[d.getMonth()]}`
  const sorted = [...entries].sort((a, b) => {
    if (!a.time && !b.time) return 0
    if (!a.time) return 1
    if (!b.time) return -1
    return a.time.localeCompare(b.time)
  })

  const popupW = 360
  const vw = window.innerWidth
  const vh = window.innerHeight
  let left = rect.right + 10
  if (left + popupW > vw - 12) left = rect.left - popupW - 10
  left = Math.max(8, left)
  let top = rect.top
  const estimatedH = Math.min(entries.length * 110 + 50, 520)
  if (top + estimatedH > vh - 12) top = Math.max(8, vh - estimatedH - 12)

  return (
    <div
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      style={{
      position: 'fixed', top, left, width: popupW,
      background: '#fff', borderRadius: 12,
      boxShadow: '0 8px 40px rgba(0,0,0,0.22)',
      border: '1px solid #e2e8f0', zIndex: 850,
      padding: '14px 16px',
      maxHeight: 520, overflow: 'hidden',
    }}>
      <div style={{ fontWeight: 700, fontSize: 15, color: '#1e293b', marginBottom: 10, borderBottom: '1px solid #f1f5f9', paddingBottom: 8 }}>
        {label} · <span style={{ fontWeight: 500, color: '#64748b' }}>{entries.length} {entries.length === 1 ? t('schedule.entriesCount_one') : t('schedule.entriesCount_other')}</span>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 9, overflowY: 'auto', maxHeight: 440 }}>
        {sorted.map(entry => {
          const meta = taskMeta(entry.taskType)
          const jobClient = entry.job ? (entry.job.quoteTo || entry.job.client?.name || entry.job.companyName || null) : null
          const rangeLabel = formatRangeLabel(entryStartStr(entry), entryEndStr(entry))
          return (
            <div key={entry.id} style={{ background: meta.bg, borderRadius: 8, padding: '10px 12px', border: `1px solid ${meta.color}33` }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 6 }}>
                <span style={{ background: meta.color, color: '#fff', borderRadius: 5, padding: '3px 9px', fontSize: 12, fontWeight: 700 }}>{meta.label}</span>
                {entry.time && <span style={{ fontSize: 14, color: '#64748b', marginLeft: 'auto', fontWeight: 700 }}>{entry.time}</span>}
              </div>
              <div style={{ fontSize: 16, fontWeight: 700, color: '#1e293b', lineHeight: 1.3 }}>{entry.description}</div>
              {rangeLabel && <div style={{ fontSize: 13, color: '#64748b', marginTop: 4 }}>🗓 {rangeLabel}</div>}
              {entry.assignedTo && (
                <div style={{ fontSize: 13, color: '#0369a1', marginTop: 4, fontWeight: 600 }}>👤 {entry.assignedTo.name}</div>
              )}
              {entry.job && (
                <Link
                  to={`/jobs/${entry.job.id}`}
                  style={{ display: 'block', fontSize: 13, color: '#0369a1', marginTop: 5, fontWeight: 600, textDecoration: 'none' }}
                >
                  📦 #{entry.job.jobNumber}{jobClient ? ` — ${jobClient}` : ''}
                </Link>
              )}
              {entry.notes && (
                <div style={{ fontSize: 13, color: '#475569', marginTop: 4, fontStyle: 'italic', lineHeight: 1.5, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                  {entry.notes}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── Main Schedule Page ────────────────────────────────────────────────────────
export default function SchedulePage() {
  const { t } = useLanguage()
  const today = new Date()

  const [year,  setYear]  = useState(today.getFullYear())
  const [month, setMonth] = useState(today.getMonth())  // 0-indexed
  const [entries, setEntries] = useState([])
  const [loading, setLoading] = useState(true)
  const [view,    setView]    = useState(() => localStorage.getItem('schedule.view') || 'calendar') // 'calendar' | 'list'
  const [dayPanel,  setDayPanel]  = useState(null)  // dateStr
  const [editEntry, setEditEntry] = useState(undefined) // undefined = closed, null = new, object = edit
  const [newDefaultDate, setNewDefaultDate] = useState('')
  const [hoveredDay, setHoveredDay] = useState(null)   // dateStr
  const [hoverRect,  setHoverRect]  = useState(null)   // DOMRect
  const isHoveringPopupRef = useRef(false)
  const hideHoverTimeoutRef = useRef(null)
  const listContainerRef = useRef(null)
  const monthStartStr = `${year}-${pad2(month + 1)}-01`
  const monthEndStr = `${year}-${pad2(month + 1)}-${pad2(new Date(year, month + 1, 0).getDate())}`

  // Scroll list view so today is centred when first shown or month changes
  useEffect(() => {
    if (view !== 'list' || loading) return
    const el = listContainerRef.current
    if (!el) return
    const isCurrentMonth = year === today.getFullYear() && month === today.getMonth()
    if (isCurrentMonth) {
      const COL_W = 240
      const scrollTo = (today.getDate() - 1) * COL_W - el.clientWidth / 2 + COL_W / 2
      el.scrollLeft = Math.max(0, scrollTo)
    } else {
      el.scrollLeft = 0
    }
  }, [view, loading, year, month]) // eslint-disable-line

  // Fetch entries overlapping the current month
  const fetchEntries = useCallback(() => {
    setLoading(true)
    api.get(`/schedule?from=${monthStartStr}&to=${monthEndStr}`)
      .then(data => setEntries(data))
      .catch(() => setEntries([]))
      .finally(() => setLoading(false))
  }, [monthEndStr, monthStartStr])

  useEffect(() => { fetchEntries() }, [fetchEntries])

  useEffect(() => {
    return () => {
      if (hideHoverTimeoutRef.current) clearTimeout(hideHoverTimeoutRef.current)
    }
  }, [])

  const clearHoverHideTimer = () => {
    if (hideHoverTimeoutRef.current) {
      clearTimeout(hideHoverTimeoutRef.current)
      hideHoverTimeoutRef.current = null
    }
  }

  const scheduleHoverHide = () => {
    clearHoverHideTimer()
    hideHoverTimeoutRef.current = setTimeout(() => {
      if (!isHoveringPopupRef.current) {
        setHoveredDay(null)
        setHoverRect(null)
      }
    }, 180)
  }

  // Group by date string, sorted by time within each day
  const byDate = {}
  entries.forEach(e => {
    expandDateRange(entryStartStr(e), entryEndStr(e))
      .filter(ds => ds >= monthStartStr && ds <= monthEndStr)
      .forEach(ds => {
        if (!byDate[ds]) byDate[ds] = []
        byDate[ds].push(e)
      })
  })
  const timeSort = (a, b) => {
    if (!a.time && !b.time) return 0
    if (!a.time) return 1
    if (!b.time) return -1
    return a.time.localeCompare(b.time)
  }
  Object.values(byDate).forEach(arr => arr.sort(timeSort))

  // ── Navigation ────────────────────────────────────────────────────────────
  const prevMonth = () => {
    if (month === 0) { setYear(y => y - 1); setMonth(11) }
    else setMonth(m => m - 1)
    setDayPanel(null)
  }
  const nextMonth = () => {
    if (month === 11) { setYear(y => y + 1); setMonth(0) }
    else setMonth(m => m + 1)
    setDayPanel(null)
  }
  const goToday = () => { setYear(today.getFullYear()); setMonth(today.getMonth()); setDayPanel(null) }

  // ── Entry CRUD ────────────────────────────────────────────────────────────
  const handleSaved = (saved, mode, deletedId) => {
    if (mode === 'delete') {
      setEntries(prev => prev.filter(e => e.id !== deletedId))
    } else if (mode === true) { // edit
      setEntries(prev => prev.map(e => e.id === saved.id ? saved : e))
    } else { // create
      setEntries(prev => [...prev, saved])
    }
    setEditEntry(undefined)
    setDayPanel(null)
  }

  const openNewEntry = (dateStr) => {
    setNewDefaultDate(dateStr)
    setEditEntry(null)
    setDayPanel(null)
  }

  const openEditEntry = (entry) => {
    setEditEntry(entry)
    setDayPanel(null)
  }

  // ── Calendar grid ─────────────────────────────────────────────────────────
  const firstDay = new Date(year, month, 1).getDay() // 0=Sun
  const daysInMonth = new Date(year, month + 1, 0).getDate()
  const todayStr = toDateStr(today)

  const cells = []
  for (let i = 0; i < firstDay; i++) cells.push(null)
  for (let d = 1; d <= daysInMonth; d++) {
    cells.push(new Date(year, month, d))
  }
  const totalCells = Math.ceil(cells.length / 7) * 7
  while (cells.length < totalCells) cells.push(null)

  const DAYS = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header" style={{ marginBottom: 16 }}>
        <div>
          <h1 className="page-title">{t('nav.schedule')}</h1>
          <p className="page-subtitle" style={{ margin: 0 }}>{MONTH_NAMES_ES[month]} {year}</p>
        </div>
        <div style={{ display:'flex', gap:8, alignItems:'center' }}>
          <button className="btn btn-ghost" onClick={goToday} style={{ fontSize:13 }}>Hoy</button>
          <button className="btn btn-ghost" onClick={() => { const next = view === 'calendar' ? 'list' : 'calendar'; setView(next); localStorage.setItem('schedule.view', next) }} style={{ fontSize:13 }}>
            {view === 'calendar' ? '☰ Lista' : '🗓 Calendario'}
          </button>
          <button className="btn btn-primary" onClick={() => openNewEntry(todayStr)}>+ Agregar</button>
        </div>
      </div>

      {/* Month nav */}
      <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:16 }}>
        <button className="btn btn-ghost" onClick={prevMonth} style={{ padding:'4px 12px' }}>‹</button>
        <span style={{ fontWeight:700, fontSize:16, minWidth:180, textAlign:'center' }}>{MONTH_NAMES_ES[month]} {year}</span>
        <button className="btn btn-ghost" onClick={nextMonth} style={{ padding:'4px 12px' }}>›</button>
      </div>

      {loading && <div style={{ textAlign:'center', padding:40, color:'#94a3b8' }}>{t('schedule.loading')}</div>}

      {/* ── CALENDAR VIEW ── */}
      {!loading && view === 'calendar' && (
        <div style={{ border:'1px solid #e2e8f0', borderRadius:12, overflow:'hidden', background:'#fff' }}>
          {/* Day headers */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)', borderBottom:'2px solid #e2e8f0' }}>
            {DAYS.map(d => (
              <div key={d} style={{ padding:'8px 0', textAlign:'center', fontSize:12, fontWeight:700, color:'#64748b', background:'#f8fafc' }}>{d}</div>
            ))}
          </div>

          {/* Weeks */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)', gridAutoRows:'130px' }}>
            {cells.map((date, i) => {
              if (!date) return (
                <div key={`empty-${i}`} style={{ background:'#f8fafc', borderRight: i % 7 < 6 ? '1px solid #e2e8f0' : 'none', borderBottom:'1px solid #e2e8f0', overflow:'hidden' }} />
              )
              const ds = toDateStr(date)
              const dayEntries = byDate[ds] || []
              const isToday = ds === todayStr
              const isSelected = dayPanel === ds

              return (
                <div key={ds}
                  onClick={() => setDayPanel(ds === dayPanel ? null : ds)}
                  onMouseEnter={e => {
                    if ((byDate[ds] || []).length > 0) {
                      clearHoverHideTimer()
                      isHoveringPopupRef.current = false
                      setHoveredDay(ds)
                      setHoverRect(e.currentTarget.getBoundingClientRect())
                    }
                  }}
                  onMouseLeave={scheduleHoverHide}
                  style={{
                    padding:4, cursor:'pointer', overflow:'hidden',
                    display:'flex', flexDirection:'column',
                    borderRight: i % 7 < 6 ? '1px solid #e2e8f0' : 'none',
                    borderBottom:'1px solid #e2e8f0',
                    background: isSelected ? '#eff6ff' : isToday ? '#fff7ed' : '#fff',
                    transition: 'background 0.1s',
                  }}
                >
                  <div style={{
                    width:24, height:24, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center',
                    fontSize:12, fontWeight: isToday ? 800 : 500,
                    color: isToday ? '#fff' : '#1e293b',
                    background: isToday ? '#f97316' : 'transparent',
                    flexShrink:0, marginBottom:2,
                  }}>{date.getDate()}</div>

                  <div style={{ flex:1, overflowY:'auto' }}>
                    {dayEntries.map(entry => {
                      const meta = taskMeta(entry.taskType)
                      const jobLabel = entry.job ? `#${entry.job.jobNumber}${entry.job.quoteTo ? ' · ' + entry.job.quoteTo : entry.job.client?.name ? ' · ' + entry.job.client.name : ''}` : null
                      const rangeLabel = formatRangeLabel(entryStartStr(entry), entryEndStr(entry))
                      return (
                        <div key={entry.id}
                          onClick={e => { e.stopPropagation(); openEditEntry(entry) }}
                          style={{
                            background:meta.bg, color:meta.color,
                            borderRadius:4, padding:'3px 5px', fontSize:10, fontWeight:600,
                            marginBottom:2, cursor:'pointer',
                          }}
                          title={[entry.description, entry.notes, jobLabel].filter(Boolean).join('\n')}
                        >
                          <div style={{ display:'flex', justifyContent:'space-between', gap:2 }}>
                            <span style={{ overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', flex:1, fontSize:11, fontWeight:700 }}>
                              {entry.time ? `${entry.time} ` : ''}{entry.description}
                            </span>
                          </div>
                          {jobLabel && (
                            <Link
                              to={`/jobs/${entry.job.id}`}
                              onClick={e => e.stopPropagation()}
                              onMouseDown={e => e.stopPropagation()}
                              style={{ display:'block', fontSize:9, opacity:0.85, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontWeight:600, color:meta.color, textDecoration:'none' }}
                            >
                              📦 {jobLabel}
                            </Link>
                          )}
                          {rangeLabel && (
                            <div style={{ fontSize:9, opacity:0.75, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontWeight:500 }}>
                              🗓 {rangeLabel}
                            </div>
                          )}
                          {entry.notes && (
                            <div style={{ fontSize:9, opacity:0.65, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontWeight:400, fontStyle:'italic' }}>
                              {entry.notes}
                            </div>
                          )}
                        </div>
                      )
                    })}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* ── LIST VIEW ── */}
      {!loading && view === 'list' && (() => {
        const COL_W = 240
        const days = Array.from({ length: daysInMonth }, (_, i) => i + 1)
        const DAY_ABBR = ['Dom','Lun','Mar','Mié','Jue','Vie','Sáb']
        return (
          <div ref={listContainerRef} style={{ overflowX:'auto', overflowY:'hidden', border:'1px solid #e2e8f0', borderRadius:12, background:'#fff', height:'calc(100vh - 220px)' }}>
            <div style={{ display:'flex', minWidth: COL_W * daysInMonth, height:'100%' }}>
              {days.map(d => {
                const date = new Date(year, month, d)
                const ds = toDateStr(date)
                const isToday = ds === todayStr
                const dayEntries = [...(byDate[ds] || [])].sort((a, b) => {
                  if (!a.time && !b.time) return 0
                  if (!a.time) return 1
                  if (!b.time) return -1
                  return a.time.localeCompare(b.time)
                })
                const dow = DAY_ABBR[date.getDay()]
                const isWeekend = date.getDay() === 0 || date.getDay() === 6
                return (
                  <div key={ds} style={{
                    width: COL_W, minWidth: COL_W, flexShrink: 0,
                    borderRight: d < daysInMonth ? '1px solid #e2e8f0' : 'none',
                    display:'flex', flexDirection:'column', height: '100%',
                    background: isToday ? '#fff7ed' : isWeekend ? '#f8fafc' : '#fff',
                  }}>
                    {/* Day header */}
                    <div style={{
                      padding:'8px 0 6px', textAlign:'center', borderBottom:'2px solid #e2e8f0',
                      background: isToday ? '#f97316' : isWeekend ? '#f1f5f9' : '#f8fafc',
                      position:'sticky', top:0, zIndex:1,
                    }}>
                      <div style={{ fontSize:18, fontWeight:800, color: isToday ? '#fff' : '#1e293b', lineHeight:1 }}>{d}</div>
                      <div style={{ fontSize:11, fontWeight:600, color: isToday ? '#fed7aa' : '#64748b', marginTop:2 }}>{dow}</div>
                    </div>

                    {/* Entries */}
                    <div style={{ flex:1, padding:8, display:'flex', flexDirection:'column', gap:7, overflowY:'auto' }}>
                      {dayEntries.map(entry => {
                        const meta = taskMeta(entry.taskType)
                        const jobClient = entry.job ? (entry.job.quoteTo || entry.job.client?.name || entry.job.companyName || null) : null
                        const rangeLabel = formatRangeLabel(entryStartStr(entry), entryEndStr(entry))
                        return (
                          <div key={entry.id}
                            onClick={() => openEditEntry(entry)}
                            style={{
                              background: meta.bg, borderRadius:8, padding:'9px 11px',
                              cursor:'pointer', border:`1px solid ${meta.color}33`,
                            }}
                          >
                            <div style={{ display:'flex', alignItems:'center', gap:5, marginBottom:4 }}>
                              <span style={{ background: meta.color, color:'#fff', borderRadius:4, padding:'2px 7px', fontSize:11, fontWeight:700 }}>{meta.label}</span>
                              {entry.time && <span style={{ fontSize:12, color:'#64748b', marginLeft:'auto', whiteSpace:'nowrap', fontWeight:600 }}>{entry.time}</span>}
                            </div>
                            <div style={{ fontSize:14, fontWeight:700, color:'#1e293b', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }} title={entry.description}>
                              {entry.description}
                            </div>
                            {rangeLabel && (
                              <div style={{ fontSize:12, color:'#64748b', marginTop:3, fontWeight:600, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>
                                🗓 {rangeLabel}
                              </div>
                            )}
                            {entry.assignedTo && (
                              <div style={{ fontSize:12, color:'#0369a1', marginTop:3, fontWeight:600, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>👤 {entry.assignedTo.name}</div>
                            )}
                            {entry.job && (
                              <Link
                                to={`/jobs/${entry.job.id}`}
                                onClick={e => e.stopPropagation()}
                                style={{ display:'block', marginTop:4, background:'#e0f2fe', color:'#0369a1', borderRadius:5, padding:'3px 7px', fontSize:11, fontWeight:600, textDecoration:'none', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}
                              >
                                📦 #{entry.job.jobNumber}{entry.job.type ? ` [${entry.job.type}]` : ''}{jobClient ? ` — ${jobClient}` : ''}
                              </Link>
                            )}
                            {entry.notes && (
                              <div style={{ fontSize:12, color:'#475569', marginTop:4, fontStyle:'italic', display:'-webkit-box', WebkitLineClamp:3, WebkitBoxOrient:'vertical', overflow:'hidden', lineHeight:'1.5' }}>
                                {entry.notes}
                              </div>
                            )}
                          </div>
                        )
                      })}
                    </div>

                    {/* Add button */}
                    <div style={{ padding:'4px 6px 6px' }}>
                      <button
                        onClick={() => openNewEntry(ds)}
                        style={{
                          width:'100%', border:'1px dashed #cbd5e1', borderRadius:6,
                          background:'transparent', color:'#94a3b8', fontSize:12,
                          padding:'4px 0', cursor:'pointer',
                        }}
                      >+</button>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )
      })()}

      {/* Day hover popup */}
      {hoveredDay && hoverRect && (
        <DayPopup
          dateStr={hoveredDay}
          entries={byDate[hoveredDay] || []}
          rect={hoverRect}
          onMouseEnter={() => {
            clearHoverHideTimer()
            isHoveringPopupRef.current = true
          }}
          onMouseLeave={() => {
            isHoveringPopupRef.current = false
            scheduleHoverHide()
          }}
        />
      )}

      {/* Day panel */}
      {dayPanel && (
        <DayPanel
          dateStr={dayPanel}
          entries={byDate[dayPanel] || []}
          onClose={() => setDayPanel(null)}
          onAdd={openNewEntry}
          onEdit={openEditEntry}
        />
      )}

      {/* Create/Edit modal */}
      {editEntry !== undefined && (
        <EntryModal
          entry={editEntry}
          defaultDate={newDefaultDate}
          onClose={() => setEditEntry(undefined)}
          onSaved={handleSaved}
        />
      )}
    </div>
  )
}
