import { useState, useEffect, useCallback, useRef } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../../api'
import { useLanguage } from '../../i18n'

// ── Task type metadata ────────────────────────────────────────────────────────
const TASK_TYPES = [
  { value: 'EMPAQUE',             label: 'Empaque',              bg: '#dbeafe', color: '#1d4ed8' },
  { value: 'MUDANZA',             label: 'Mudanza',              bg: '#e0e7ff', color: '#4338ca' },
  { value: 'DESEMPAQUE',          label: 'Desempaque',           bg: '#ccfbf1', color: '#0f766e' },
  { value: 'CARGA_CONTENEDOR',    label: 'Carga Contenedor',     bg: '#ffedd5', color: '#c2410c' },
  { value: 'TRABAJO_INDUSTRIAL',  label: 'Trabajo Industrial',   bg: '#fef9c3', color: '#a16207' },
  { value: 'ENTREGA',             label: 'Entrega',              bg: '#dcfce7', color: '#15803d' },
  { value: 'TRASLADO_BODEGA',     label: 'Traslado Bodega',      bg: '#fef3c7', color: '#b45309' },
  { value: 'VISITA',              label: 'Visita',               bg: '#f3e8ff', color: '#7e22ce' },
  { value: 'OTRO',                label: 'Otro',                 bg: '#f1f5f9', color: '#475569' },
]
const taskMeta = (type) => TASK_TYPES.find(t => t.value === type) || TASK_TYPES[TASK_TYPES.length - 1]

const MONTH_NAMES_ES = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']

function pad2(n) { return String(n).padStart(2, '0') }
function toDateStr(d) { return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}` }

// ── Empty form ────────────────────────────────────────────────────────────────
const EMPTY_FORM = {
  date: '', time: '', taskType: 'EMPAQUE', description: '', notes: '',
  jobId: '',
}

// ── Linked record chip ────────────────────────────────────────────────────────
function LinkedChip({ entry }) {
  if (entry.job) return <Link to={`/jobs/${entry.job.id}`} className="badge" style={{ background:'#e0f2fe', color:'#0369a1', textDecoration:'none', fontSize:11 }}>#{entry.job.jobNumber}</Link>
  return null
}

// ── Create/Edit Modal ─────────────────────────────────────────────────────────
function EntryModal({ entry, defaultDate, onClose, onSaved }) {
  const isEdit = Boolean(entry?.id)
  const isSystem = isEdit && Boolean(entry.isAutoGenerated)
  const [form, setForm] = useState(EMPTY_FORM)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState(null)
  const [jobSearch, setJobSearch] = useState('')
  const [jobResults, setJobResults] = useState([])
  const [jobSearching, setJobSearching] = useState(false)
  const [selectedJob, setSelectedJob] = useState(null)

  useEffect(() => {
    if (entry) {
      setForm({
        date:         entry.date.slice(0, 10),
        time:         entry.time         || '',
        taskType:     entry.taskType,
        description:  entry.description,
        notes:        entry.notes        || '',
        jobId:        entry.jobId        || '',
      })
      setSelectedJob(entry.job || null)
    } else {
      setForm({ ...EMPTY_FORM, date: defaultDate || '' })
      setSelectedJob(null)
    }
  }, [entry, defaultDate])

  // Debounced job search
  useEffect(() => {
    if (!jobSearch.trim() || form.jobId) { setJobResults([]); return }
    const t = setTimeout(() => {
      setJobSearching(true)
      api.get(`/jobs?search=${encodeURIComponent(jobSearch.trim())}`)
        .then(data => setJobResults((data || []).slice(0, 8)))
        .catch(() => setJobResults([]))
        .finally(() => setJobSearching(false))
    }, 300)
    return () => clearTimeout(t)
  }, [jobSearch, form.jobId])

  const set = (f, v) => setForm(p => ({ ...p, [f]: v }))

  const handleSubmit = async (e) => {
    e.preventDefault()
    setSaving(true)
    setError(null)
    try {
      const payload = {
        date:         form.date,
        time:         form.time || null,
        taskType:     form.taskType,
        description:  form.description,
        notes:        form.notes        || null,
        jobId:        form.jobId        || null,
      }
      const saved = isEdit
        ? await api.put(`/schedule/${entry.id}`, payload)
        : await api.post('/schedule', payload)
      onSaved(saved, isEdit)
    } catch (err) {
      setError(err.message)
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!window.confirm('¿Eliminar esta entrada?')) return
    setSaving(true)
    setError(null)
    try {
      await api.delete(`/schedule/${entry.id}`)
      onSaved(null, 'delete', entry.id)
    } catch (err) {
      setError(err.message)
      setSaving(false)
    }
  }

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.45)', zIndex:1000, display:'flex', alignItems:'center', justifyContent:'center', padding:16 }}>
      <div style={{ background:'#fff', borderRadius:12, padding:24, width:'100%', maxWidth:480, maxHeight:'90vh', overflowY:'auto', boxShadow:'0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:20 }}>
          <h3 style={{ margin:0, fontSize:16, fontWeight:700 }}>{isEdit ? 'Editar entrada' : 'Nueva entrada'}</h3>
          <button onClick={onClose} style={{ background:'none', border:'none', fontSize:20, cursor:'pointer', color:'#64748b' }}>✕</button>
        </div>

        <form onSubmit={handleSubmit} style={{ display:'flex', flexDirection:'column', gap:14 }}>
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12 }}>
            <div className="form-group">
              <label className="form-label">Fecha *</label>
              <input className="form-control" type="date" value={form.date} onChange={e => set('date', e.target.value)}
                required />
            </div>
            <div className="form-group">
              <label className="form-label">Hora *</label>
              <input className="form-control" type="time" value={form.time}
                onChange={e => set('time', e.target.value)} required />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Tipo de tarea *</label>
            <select className="form-control" value={form.taskType} onChange={e => set('taskType', e.target.value)} required>
              {TASK_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
            </select>
          </div>

          <div className="form-group">
            <label className="form-label">Descripción *</label>
            <input className="form-control" value={form.description} onChange={e => set('description', e.target.value)}
              required placeholder="Descripción del trabajo..." />
          </div>

          <div className="form-group">
            <label className="form-label">Notas</label>
            <textarea className="form-control" rows={2} value={form.notes} onChange={e => set('notes', e.target.value)} placeholder="Notas internas..." />
          </div>

          {(selectedJob || !isSystem) && (
            <div className="form-group">
              <label className="form-label">{isSystem ? 'Trabajo vinculado' : 'Vincular a Trabajo (opcional)'}</label>
              {form.jobId && selectedJob ? (
                <div style={{ display:'flex', alignItems:'center', gap:8, padding:'8px 10px', background:'#e0f2fe', borderRadius:6 }}>
                  <span style={{ fontWeight:700, fontSize:13 }}>#{selectedJob.jobNumber}</span>
                  {selectedJob.type && <span style={{ fontSize:11, fontWeight:600, background:'#bfdbfe', color:'#1d4ed8', borderRadius:4, padding:'1px 6px' }}>{selectedJob.type}</span>}
                  <span style={{ flex:1, fontSize:13, color:'#0369a1' }}>{selectedJob.quoteTo || selectedJob.client?.name || selectedJob.companyName || '—'}</span>
                  {!isSystem && <button type="button"
                    onClick={() => { set('jobId', ''); setSelectedJob(null); setJobSearch('') }}
                    style={{ background:'none', border:'none', color:'#64748b', cursor:'pointer', fontSize:16, lineHeight:1 }}>✕</button>}
                </div>
              ) : (
                !isSystem && <div style={{ position:'relative' }}>
                  <input className="form-control" placeholder="Buscar por # trabajo o nombre de cliente..."
                    value={jobSearch} onChange={e => setJobSearch(e.target.value)} />
                  {jobSearching && <div style={{ fontSize:12, color:'#64748b', marginTop:4 }}>Buscando...</div>}
                  {jobResults.length > 0 && (
                    <div style={{ position:'absolute', top:'100%', left:0, right:0, background:'#fff', border:'1px solid #e2e8f0', borderRadius:8, boxShadow:'0 4px 16px rgba(0,0,0,0.12)', zIndex:20, maxHeight:200, overflowY:'auto', marginTop:2 }}>
                      {jobResults.map(j => {
                          const typeColors = { EXPORT:'#dbeafe|#1d4ed8', IMPORT:'#dcfce7|#15803d', INTERNATIONAL:'#f3e8ff|#7e22ce', DOMESTIC:'#fef9c3|#a16207' }
                          const [tbg, tcol] = (typeColors[j.type] || '#f1f5f9|#475569').split('|')
                          return (
                            <div key={j.id}
                              onMouseDown={e => e.preventDefault()}
                              onClick={() => { set('jobId', j.id); setSelectedJob(j); setJobSearch(''); setJobResults([]) }}
                              style={{ padding:'8px 12px', cursor:'pointer', borderBottom:'1px solid #f1f5f9', fontSize:13, display:'flex', alignItems:'center', gap:8 }}
                            >
                              <span style={{ fontWeight:700 }}>#{j.jobNumber}</span>
                              {j.type && <span style={{ background:tbg, color:tcol, borderRadius:4, padding:'1px 6px', fontSize:11, fontWeight:600 }}>{j.type}</span>}
                              <span style={{ color:'#64748b' }}>{j.quoteTo || j.client?.name || j.companyName || '—'}</span>
                            </div>
                          )
                        })}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {error && <div className="alert alert-error" style={{ fontSize:13 }}>{error}</div>}

          <div style={{ display:'flex', justifyContent:'space-between', marginTop:4 }}>
            {isEdit && !isSystem
              ? <button type="button" onClick={handleDelete} className="btn" style={{ background:'#fee2e2', color:'#b91c1c', border:'none' }} disabled={saving}>Eliminar</button>
              : <span />}
            <div style={{ display:'flex', gap:8 }}>
              <button type="button" className="btn btn-ghost" onClick={onClose} disabled={saving}>Cancelar</button>
              <button type="submit" className="btn btn-primary" disabled={saving}>{saving ? 'Guardando...' : 'Guardar'}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}

// ── Day Panel ─────────────────────────────────────────────────────────────────
function DayPanel({ dateStr, entries, onClose, onAdd, onEdit }) {
  const dayEntries = [...entries].sort((a, b) => {
    if (!a.time && !b.time) return 0
    if (!a.time) return 1
    if (!b.time) return -1
    return a.time.localeCompare(b.time)
  })
  const d = new Date(dateStr + 'T12:00:00')
  const label = `${d.getDate()} de ${MONTH_NAMES_ES[d.getMonth()]} ${d.getFullYear()}`

  return (
    <div style={{ position:'fixed', inset:0, zIndex:900, display:'flex' }}>
      <div style={{ flex:1 }} onClick={onClose} />
      <div style={{ width: 360, background:'#fff', boxShadow:'-4px 0 24px rgba(0,0,0,0.15)', display:'flex', flexDirection:'column', overflowY:'auto' }}>
        <div style={{ padding:'16px 20px', borderBottom:'1px solid #e2e8f0', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
          <div>
            <div style={{ fontWeight:700, fontSize:15 }}>{label}</div>
            <div style={{ fontSize:12, color:'#64748b' }}>{dayEntries.length} {dayEntries.length === 1 ? 'entrada' : 'entradas'}</div>
          </div>
          <button onClick={onClose} style={{ background:'none', border:'none', fontSize:20, cursor:'pointer', color:'#64748b' }}>✕</button>
        </div>

        <div style={{ flex:1, padding:'12px 16px', display:'flex', flexDirection:'column', gap:10 }}>
          {dayEntries.length === 0 && <div style={{ color:'#94a3b8', fontSize:13, textAlign:'center', marginTop:16 }}>Sin entradas para este día.</div>}
          {dayEntries.map(entry => {
            const meta = taskMeta(entry.taskType)
            return (
              <div key={entry.id} onClick={() => onEdit(entry)}
                style={{ border:'1px solid #e2e8f0', borderRadius:8, padding:'10px 12px', cursor:'pointer', background:'#fafafa' }}
              >
                <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:4 }}>
                  <span style={{ background:meta.bg, color:meta.color, borderRadius:4, padding:'2px 7px', fontSize:11, fontWeight:600 }}>{meta.label}</span>
                  {entry.time && <span style={{ fontSize:12, color:'#64748b' }}>{entry.time}</span>}
                  <LinkedChip entry={entry} />
                </div>
                <div style={{ fontSize:13, fontWeight:600, color:'#1e293b' }}>{entry.description}</div>
                {entry.notes && <div style={{ fontSize:12, color:'#94a3b8', marginTop:2, fontStyle:'italic' }}>{entry.notes}</div>}
              </div>
            )
          })}
        </div>

        <div style={{ padding:'12px 16px', borderTop:'1px solid #e2e8f0' }}>
          <button className="btn btn-primary" style={{ width:'100%' }} onClick={() => onAdd(dateStr)}>+ Agregar entrada</button>
        </div>
      </div>
    </div>
  )
}

// ── Main Schedule Page ────────────────────────────────────────────────────────
export default function SchedulePage() {
  const { t } = useLanguage()
  const today = new Date()

  const [year,  setYear]  = useState(today.getFullYear())
  const [month, setMonth] = useState(today.getMonth())  // 0-indexed
  const [entries, setEntries] = useState([])
  const [loading, setLoading] = useState(true)
  const [view,    setView]    = useState('calendar') // 'calendar' | 'list'
  const [dayPanel,  setDayPanel]  = useState(null)  // dateStr
  const [editEntry, setEditEntry] = useState(undefined) // undefined = closed, null = new, object = edit
  const [newDefaultDate, setNewDefaultDate] = useState('')
  const listContainerRef = useRef(null)

  // Scroll list view so today is centred when first shown or month changes
  useEffect(() => {
    if (view !== 'list' || loading) return
    const el = listContainerRef.current
    if (!el) return
    const isCurrentMonth = year === today.getFullYear() && month === today.getMonth()
    if (isCurrentMonth) {
      const COL_W = 130
      const scrollTo = (today.getDate() - 1) * COL_W - el.clientWidth / 2 + COL_W / 2
      el.scrollLeft = Math.max(0, scrollTo)
    } else {
      el.scrollLeft = 0
    }
  }, [view, loading, year, month]) // eslint-disable-line

  // Fetch entries for current month
  const fetchEntries = useCallback(() => {
    const pad2 = n => String(n).padStart(2, '0')
    const lastDay = new Date(year, month + 1, 0).getDate()
    const from = `${year}-${pad2(month + 1)}-01`
    const to   = `${year}-${pad2(month + 1)}-${pad2(lastDay)}`
    setLoading(true)
    api.get(`/schedule?from=${from}&to=${to}`)
      .then(data => setEntries(data))
      .catch(() => setEntries([]))
      .finally(() => setLoading(false))
  }, [year, month])

  useEffect(() => { fetchEntries() }, [fetchEntries])

  // Group by date string, sorted by time within each day
  const byDate = {}
  entries.forEach(e => {
    const ds = e.date.slice(0, 10)
    if (!byDate[ds]) byDate[ds] = []
    byDate[ds].push(e)
  })
  const timeSort = (a, b) => {
    if (!a.time && !b.time) return 0
    if (!a.time) return 1
    if (!b.time) return -1
    return a.time.localeCompare(b.time)
  }
  Object.values(byDate).forEach(arr => arr.sort(timeSort))

  // ── Navigation ────────────────────────────────────────────────────────────
  const prevMonth = () => {
    if (month === 0) { setYear(y => y - 1); setMonth(11) }
    else setMonth(m => m - 1)
    setDayPanel(null)
  }
  const nextMonth = () => {
    if (month === 11) { setYear(y => y + 1); setMonth(0) }
    else setMonth(m => m + 1)
    setDayPanel(null)
  }
  const goToday = () => { setYear(today.getFullYear()); setMonth(today.getMonth()); setDayPanel(null) }

  // ── Entry CRUD ────────────────────────────────────────────────────────────
  const handleSaved = (saved, mode, deletedId) => {
    if (mode === 'delete') {
      setEntries(prev => prev.filter(e => e.id !== deletedId))
    } else if (mode === true) { // edit
      setEntries(prev => prev.map(e => e.id === saved.id ? saved : e))
    } else { // create
      setEntries(prev => [...prev, saved])
    }
    setEditEntry(undefined)
    setDayPanel(null)
  }

  const openNewEntry = (dateStr) => {
    setNewDefaultDate(dateStr)
    setEditEntry(null)
    setDayPanel(null)
  }

  const openEditEntry = (entry) => {
    setEditEntry(entry)
    setDayPanel(null)
  }

  // ── Calendar grid ─────────────────────────────────────────────────────────
  const firstDay = new Date(year, month, 1).getDay() // 0=Sun
  const daysInMonth = new Date(year, month + 1, 0).getDate()
  const todayStr = toDateStr(today)

  const cells = []
  for (let i = 0; i < firstDay; i++) cells.push(null)
  for (let d = 1; d <= daysInMonth; d++) {
    cells.push(new Date(year, month, d))
  }
  const totalCells = Math.ceil(cells.length / 7) * 7
  while (cells.length < totalCells) cells.push(null)

  const DAYS = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header" style={{ marginBottom: 16 }}>
        <div>
          <h1 className="page-title">{t('nav.schedule')}</h1>
          <p className="page-subtitle" style={{ margin: 0 }}>{MONTH_NAMES_ES[month]} {year}</p>
        </div>
        <div style={{ display:'flex', gap:8, alignItems:'center' }}>
          <button className="btn btn-ghost" onClick={goToday} style={{ fontSize:13 }}>Hoy</button>
          <button className="btn btn-ghost" onClick={() => setView(v => v === 'calendar' ? 'list' : 'calendar')} style={{ fontSize:13 }}>
            {view === 'calendar' ? '☰ Lista' : '🗓 Calendario'}
          </button>
          <button className="btn btn-primary" onClick={() => openNewEntry(todayStr)}>+ Agregar</button>
        </div>
      </div>

      {/* Month nav */}
      <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:16 }}>
        <button className="btn btn-ghost" onClick={prevMonth} style={{ padding:'4px 12px' }}>‹</button>
        <span style={{ fontWeight:700, fontSize:16, minWidth:180, textAlign:'center' }}>{MONTH_NAMES_ES[month]} {year}</span>
        <button className="btn btn-ghost" onClick={nextMonth} style={{ padding:'4px 12px' }}>›</button>
      </div>

      {loading && <div style={{ textAlign:'center', padding:40, color:'#94a3b8' }}>Cargando...</div>}

      {/* ── CALENDAR VIEW ── */}
      {!loading && view === 'calendar' && (
        <div style={{ border:'1px solid #e2e8f0', borderRadius:12, overflow:'hidden', background:'#fff' }}>
          {/* Day headers */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)', borderBottom:'2px solid #e2e8f0' }}>
            {DAYS.map(d => (
              <div key={d} style={{ padding:'8px 0', textAlign:'center', fontSize:12, fontWeight:700, color:'#64748b', background:'#f8fafc' }}>{d}</div>
            ))}
          </div>

          {/* Weeks */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)' }}>
            {cells.map((date, i) => {
              if (!date) return (
                <div key={`empty-${i}`} style={{ minHeight:90, background:'#f8fafc', borderRight: i % 7 < 6 ? '1px solid #e2e8f0' : 'none', borderBottom:'1px solid #e2e8f0' }} />
              )
              const ds = toDateStr(date)
              const dayEntries = byDate[ds] || []
              const isToday = ds === todayStr
              const isSelected = dayPanel === ds
              const visible = dayEntries.slice(0, 3)
              const overflow = dayEntries.length - 3

              return (
                <div key={ds}
                  onClick={() => setDayPanel(ds === dayPanel ? null : ds)}
                  style={{
                    minHeight:90, padding:4, cursor:'pointer', position:'relative',
                    borderRight: i % 7 < 6 ? '1px solid #e2e8f0' : 'none',
                    borderBottom:'1px solid #e2e8f0',
                    background: isSelected ? '#eff6ff' : isToday ? '#fff7ed' : '#fff',
                    transition: 'background 0.1s',
                  }}
                >
                  <div style={{
                    width:24, height:24, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center',
                    fontSize:12, fontWeight: isToday ? 800 : 500,
                    color: isToday ? '#fff' : '#1e293b',
                    background: isToday ? '#f97316' : 'transparent',
                    marginBottom:2,
                  }}>{date.getDate()}</div>

                  {visible.map(entry => {
                    const meta = taskMeta(entry.taskType)
                    const jobLabel = entry.job ? `#${entry.job.jobNumber}${entry.job.quoteTo ? ' · ' + entry.job.quoteTo : entry.job.client?.name ? ' · ' + entry.job.client.name : ''}` : null
                    return (
                      <div key={entry.id}
                        onClick={e => { e.stopPropagation(); openEditEntry(entry) }}
                        style={{
                          background:meta.bg, color:meta.color,
                          borderRadius:4, padding:'3px 5px', fontSize:10, fontWeight:600,
                          marginBottom:2, cursor:'pointer',
                        }}
                        title={[entry.description, entry.notes, jobLabel].filter(Boolean).join('\n')}
                      >
                        <div style={{ display:'flex', justifyContent:'space-between', gap:2 }}>
                          <span style={{ overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', flex:1 }}>
                            {entry.time ? `${entry.time} ` : ''}{entry.description}
                          </span>
                        </div>
                        {jobLabel && (
                          <div style={{ fontSize:9, opacity:0.75, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontWeight:500 }}>
                            📦 {jobLabel}
                          </div>
                        )}
                        {entry.notes && (
                          <div style={{ fontSize:9, opacity:0.65, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontWeight:400, fontStyle:'italic' }}>
                            {entry.notes}
                          </div>
                        )}
                      </div>
                    )
                  })}
                  {overflow > 0 && (
                    <div style={{ fontSize:10, color:'#64748b', fontWeight:600, marginTop:1 }}>+{overflow} más</div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* ── LIST VIEW ── */}
      {!loading && view === 'list' && (() => {
        const COL_W = 130
        const days = Array.from({ length: daysInMonth }, (_, i) => i + 1)
        const DAY_ABBR = ['Dom','Lun','Mar','Mié','Jue','Vie','Sáb']
        return (
          <div ref={listContainerRef} style={{ overflowX:'auto', border:'1px solid #e2e8f0', borderRadius:12, background:'#fff' }}>
            <div style={{ display:'flex', minWidth: COL_W * daysInMonth }}>
              {days.map(d => {
                const date = new Date(year, month, d)
                const ds = toDateStr(date)
                const isToday = ds === todayStr
                const dayEntries = [...(byDate[ds] || [])].sort((a, b) => {
                  if (!a.time && !b.time) return 0
                  if (!a.time) return 1
                  if (!b.time) return -1
                  return a.time.localeCompare(b.time)
                })
                const dow = DAY_ABBR[date.getDay()]
                const isWeekend = date.getDay() === 0 || date.getDay() === 6
                return (
                  <div key={ds} style={{
                    width: COL_W, minWidth: COL_W, flexShrink: 0,
                    borderRight: d < daysInMonth ? '1px solid #e2e8f0' : 'none',
                    display:'flex', flexDirection:'column',
                    background: isToday ? '#fff7ed' : isWeekend ? '#f8fafc' : '#fff',
                  }}>
                    {/* Day header */}
                    <div style={{
                      padding:'8px 0 6px', textAlign:'center', borderBottom:'2px solid #e2e8f0',
                      background: isToday ? '#f97316' : isWeekend ? '#f1f5f9' : '#f8fafc',
                      position:'sticky', top:0, zIndex:1,
                    }}>
                      <div style={{ fontSize:18, fontWeight:800, color: isToday ? '#fff' : '#1e293b', lineHeight:1 }}>{d}</div>
                      <div style={{ fontSize:11, fontWeight:600, color: isToday ? '#fed7aa' : '#64748b', marginTop:2 }}>{dow}</div>
                    </div>

                    {/* Entries */}
                    <div style={{ flex:1, padding:6, display:'flex', flexDirection:'column', gap:5 }}>
                      {dayEntries.map(entry => {
                        const meta = taskMeta(entry.taskType)
                        const jobClient = entry.job ? (entry.job.quoteTo || entry.job.client?.name || entry.job.companyName || null) : null
                        return (
                          <div key={entry.id}
                            onClick={() => openEditEntry(entry)}
                            style={{
                              background: meta.bg, borderRadius:6, padding:'6px 7px',
                              cursor:'pointer', border:`1px solid ${meta.color}22`,
                            }}
                          >
                            <div style={{ display:'flex', alignItems:'center', gap:4, marginBottom:3 }}>
                              <span style={{ color:meta.color, fontSize:10, fontWeight:700 }}>{meta.label}</span>
                              {entry.time && <span style={{ fontSize:10, color:'#64748b', marginLeft:'auto', whiteSpace:'nowrap' }}>{entry.time}</span>}
                            </div>
                            <div style={{ fontSize:11, fontWeight:600, color:'#1e293b', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }} title={entry.description}>
                              {entry.description}
                            </div>
                            {entry.job && (
                              <Link
                                to={`/jobs/${entry.job.id}`}
                                onClick={e => e.stopPropagation()}
                                style={{ display:'block', marginTop:3, background:'#e0f2fe', color:'#0369a1', borderRadius:4, padding:'2px 5px', fontSize:10, fontWeight:600, textDecoration:'none', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}
                              >
                                📦 #{entry.job.jobNumber}{entry.job.type ? ` [${entry.job.type}]` : ''}{jobClient ? ` — ${jobClient}` : ''}
                              </Link>
                            )}
                            {entry.notes && (
                              <div style={{ fontSize:10, color:'#475569', marginTop:3, fontStyle:'italic', display:'-webkit-box', WebkitLineClamp:2, WebkitBoxOrient:'vertical', overflow:'hidden', lineHeight:'1.4' }}>
                                {entry.notes}
                              </div>
                            )}
                          </div>
                        )
                      })}
                    </div>

                    {/* Add button */}
                    <div style={{ padding:'4px 6px 6px' }}>
                      <button
                        onClick={() => openNewEntry(ds)}
                        style={{
                          width:'100%', border:'1px dashed #cbd5e1', borderRadius:6,
                          background:'transparent', color:'#94a3b8', fontSize:12,
                          padding:'4px 0', cursor:'pointer',
                        }}
                      >+</button>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )
      })()}

      {/* Day panel */}
      {dayPanel && (
        <DayPanel
          dateStr={dayPanel}
          entries={byDate[dayPanel] || []}
          onClose={() => setDayPanel(null)}
          onAdd={openNewEntry}
          onEdit={openEditEntry}
        />
      )}

      {/* Create/Edit modal */}
      {editEntry !== undefined && (
        <EntryModal
          entry={editEntry}
          defaultDate={newDefaultDate}
          onClose={() => setEditEntry(undefined)}
          onSaved={handleSaved}
        />
      )}
    </div>
  )
}
