const { getPrisma } = require('../db')
const { logAudit }  = require('../audit')

const SERVICE_TYPE_LABELS = {
  DOOR_TO_PORT: 'Puerta a Puerto',
  DOOR_TO_DOOR: 'Puerta a Puerta',
  PACKING:      'Empaque',
  LOCAL_MOVE:   'Mudanza Local',
  PORT_TO_DOOR: 'Puerto a Puerta',
}

/**
 * Upsert/delete EMPAQUE and MUDANZA schedule entries for a Job.
 * Called after job create or update (fire-and-forget).
 */
async function syncJobScheduleEntries(job, req = null) {
  const db = getPrisma()
  const clientLabel = job.quoteTo || job.companyName || ''
  const label = clientLabel ? ` — ${clientLabel}` : ''

  // Build notes from job details (only written on first create; preserved if user edits later)
  const noteParts = []
  if (clientLabel)           noteParts.push(`Cliente: ${clientLabel}`)
  const typeParts = [job.type, job.shipmentMode].filter(Boolean)
  if (typeParts.length)      noteParts.push(typeParts.join(' · '))
  const origin = [job.originCity, job.originCountry].filter(Boolean).join(', ')
  const dest   = [job.destCity,   job.destCountry  ].filter(Boolean).join(', ')
  if (origin || dest)        noteParts.push([origin && `Origen: ${origin}`, dest && `Destino: ${dest}`].filter(Boolean).join(' → '))
  const measures = []
  if (job.volumeCbm != null) measures.push(`${job.volumeCbm} m³`)
  if (job.weightKg  != null) measures.push(`${job.weightKg} kg`)
  if (job.bultos    != null) measures.push(`${job.bultos} bultos`)
  if (measures.length)       noteParts.push(measures.join(' · '))
  if (job.serviceDetails)    noteParts.push(job.serviceDetails)
  const notes = noteParts.length ? noteParts.join('\n') : null

  const taskType = { EXPORT: 'EMPAQUE', IMPORT: 'DESEMPAQUE' }[job.type] || 'MUDANZA'
  const taskLabel = { EMPAQUE: 'Empaque', DESEMPAQUE: 'Desempaque', MUDANZA: 'Mudanza' }[taskType]
  const description = `${taskLabel}${label}`

  // Resolve encargado: prefer MovingFile coordinator, fall back to job coordinator
  let resolvedCoordinatorId = job.coordinatorId || null
  if (job.movingFileId) {
    const mf = await db.movingFile.findUnique({
      where: { id: job.movingFileId },
      select: { coordinatorId: true },
    }).catch(() => null)
    if (mf?.coordinatorId) resolvedCoordinatorId = mf.coordinatorId
  }

  // Match any existing service entry for this job regardless of old taskType
  await _syncEntry(db, {
    matchWhere:   { jobId: job.id, taskType: { in: ['EMPAQUE', 'MUDANZA', 'DESEMPAQUE'] } },
    date:         job.serviceDate || job.moveDate,
    time:         job.serviceTime || null,
    taskType,
    description,
    notes,
    jobId:        job.id,
    assignedToId: resolvedCoordinatorId,
    req,
  })
}

/**
 * Internal helper — upsert if date is set, delete if date is null/undefined.
 */
async function _syncEntry(db, { matchWhere, date, time, taskType, description, notes, jobId, assignedToId, req = null }) {
  try {
    const existing = await db.scheduleEntry.findFirst({ where: matchWhere })

    if (!date) {
      // Date cleared — remove the entry if it exists
      if (existing) {
        await db.scheduleEntry.delete({ where: { id: existing.id } })
        if (req) logAudit(req, 'ScheduleEntry', existing.id, 'DELETE', existing, null)
      }
      return
    }

    const data = {
      date:         new Date(date),
      time:         time         || null,
      taskType,
      description,
      notes:        notes        || null,
      assignedToId: assignedToId || null,
      jobId:        jobId        || null,
    }

    if (existing) {
      // On re-sync: update structural fields from the job. Preserve user-edited notes and assignedToId.
      const updated = await db.scheduleEntry.update({
        where: { id: existing.id },
        data: { date: data.date, time: data.time, taskType: data.taskType, description: data.description },
      })
      if (req) logAudit(req, 'ScheduleEntry', existing.id, 'UPDATE', existing, updated)
    } else {
      const created = await db.scheduleEntry.create({ data: { ...data, isAutoGenerated: true } })
      if (req) logAudit(req, 'ScheduleEntry', created.id, 'CREATE', null, created)
    }
  } catch (err) {
    console.error('[scheduleSync] error:', err.message)
  }
}

module.exports = { syncJobScheduleEntries }
